name: "Build 🔨"

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: "Build 🔨"
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        platform: ['iOS', 'tvOS', 'iPadOS']

    runs-on: macos-14

    steps:    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Fetch Commit Info
        id: commitinfo
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Install SwiftGen
        run: brew install swiftgen

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Cache Carthage
        uses: actions/cache@v4
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-carthage-

      - name: Update Carthage
        run: carthage update --use-xcframeworks --cache-builds

      - name: Verify Xcode and SDK versions
        run: |
          xcodebuild -version
          xcodebuild -showsdks

      - name: Build ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" == "macOS" ]; then
            xcodebuild -project "Swiftfin.xcodeproj" -scheme Swiftfin-${{ matrix.platform }} -clonedSourcePackagesDirPath PackageCache -configuration Release -destination "platform=macOS,arch=arm64" -archivePath "build/Swiftfin.${{ matrix.platform }}.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          elif [ "${{ matrix.platform }}" == "iPadOS" ]; then
            xcodebuild -project "Swiftfin.xcodeproj" -scheme Swiftfin-${{ matrix.platform }} -clonedSourcePackagesDirPath PackageCache -configuration Release -destination 'platform=iOS Simulator,name=iPad Pro (11-inch) (4th generation),OS=latest' archive -archivePath "build/Swiftfin.${{ matrix.platform }}.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          else
            xcodebuild -project "Swiftfin.xcodeproj" -scheme Swiftfin-${{ matrix.platform }} -clonedSourcePackagesDirPath PackageCache -configuration Release -destination generic/platform=${{ matrix.platform }} archive -archivePath "build/Swiftfin.${{ matrix.platform }}.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          fi

      - name: Package ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" == "iPadOS" ]; then
            ./Misc/scripts/package.sh "build/Swiftfin.${{ matrix.platform }}.xcarchive" "macOS" "Swiftfin.${{ steps.commitinfo.outputs.sha_short }}.${{ matrix.platform }}"
          else
            ./Misc/scripts/package.sh "build/Swiftfin.${{ matrix.platform }}.xcarchive" ${{ matrix.platform }} "Swiftfin.${{ steps.commitinfo.outputs.sha_short }}.${{ matrix.platform }}"
          fi

      - name: Upload ${{ matrix.platform }} Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Swiftfin.${{ steps.commitinfo.outputs.sha_short }}.${{ matrix.platform }}
          path: build/*
          if-no-files-found: error
